# Generated by Django 5.2.7 on 2025-10-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliacao',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
